PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

# Increase CR Version with each major release.
CR_VERSION := 1.0

# Internal version
LINEAGE_VERSION := SwiftOS-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)

# Display version
LINEAGE_DISPLAY_VERSION := SwiftOS-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)
